codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down

  ignore:
    - "docs/**"
    - "android/**"
    - "lib/l10n/**"

  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: false
        if_not_found: success
    patch:
      default:
        target: 60%
        threshold: 0%
        informational: false
        if_not_found: success
        paths:
          - "lib/"
          - "test/"

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
