name: habit_tracker
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.4
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_analytics: ^12.0.2
  firebase_crashlytics: ^5.0.2
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.6
  package_info_plus: ^9.0.0
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.2.1
  flutter_native_timezone:
    path: packages/flutter_native_timezone
  flutter_localizations:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  crypto: ^3.0.5
  uuid: ^4.5.1
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.3
  flutter_launcher_icons: ^0.14.4

# Flutter configuration
flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: assets/branding/app_icon_android.png
  adaptive_icon_foreground: assets/branding/app_icon_adaptive.png
  adaptive_icon_background: "#FFFFFFFF"
  image_path_ios: assets/branding/app_icon_ios.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#041529"
  image: assets/branding/app_icon.png
  image_dark: assets/branding/app_icon.png
